// application constants
'use strict'

const FIT_MARGIN_TOP = 0.08
const FIT_MARGIN_RIGHT = 0.28
const FIT_MARGIN_LEFT = 0.06
const FIT_MARGIN_BOTTOM = 0
const FIT_WIDTH = 1 - FIT_MARGIN_RIGHT - FIT_MARGIN_LEFT
const FIT_HEIGHT = 1 - FIT_MARGIN_BOTTOM - FIT_MARGIN_TOP

module.exports = {
  ZOOM_SCALE_MIN: 0.1,
  ZOOM_SCALE_MAX: 50,

  FIT_BASE_X: 0.5 * FIT_WIDTH + FIT_MARGIN_LEFT,
  FIT_BASE_Y: 0.5 * FIT_HEIGHT + FIT_MARGIN_TOP,
  FIT_BASE_SCALE: FIT_WIDTH,

  PAN_DISCRETE_AMOUNT: 0.05
}
